name: "[Feature] Feature Request"
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: Describe the problem...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution.
      placeholder: Describe your solution...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context (Optional)
      description: Any other context about the feature request.
      placeholder: Add any other context...
