name: Deploy via Coolify

on:
  push:
    branches:
      - master # change to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Coolify deploy webhook
        run: |
          curl -X POST \
            "https://coolify.ivanangjelkoski.com/api/v1/deploy?uuid=o0so8oo0gksgok4gokgwcwcg&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            -H "Content-Type: application/json"
